version: "3.9"

services:
  db:
    image: postgres
    container_name: ptm_db
    restart: always
    environment:
      POSTGRES_USER: moesalari
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: task1
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

volumes:
  postgres_data:
