version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: fastapi_postgres
    restart: always
    environment:
      POSTGRES_USER: moesalari
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: task1
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

volumes:
  postgres_data:
